### ISSUE TITLE
WB raises error

### ISSUE THREAD

**Issue by apper002** [Alonso-JAMM/planetary_gears#2]
Hi Alanso

ThX for this WB!!

Just get this error:

cannot import name 'CreateInternalInvoluteGear' from 'freecad.gears.commands' (/home/apper/.FreeCAD/Mod/fcgear/freecad/gears/commands.py)

OS: Ubuntu 21.04 (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.19.2)
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

Rgds
Apper

**Comment by Alonso-JAMM** [comment]
This workbench uses the "develop" branch of [FCGear](https://github.com/looooo/freecad.gears/tree/develop) to generate the ring gear. The "develop" branch contains the CreateInternalInvoluteGear command. I couldn't think of a good way to create the ring gear without using that branch.

**Comment by luzpaz** [comment]
@Alonso-JAMM should this ticket be closed then ?

**Comment by Alonso-JAMM** [comment]
I haven't looked at this for a long time but now the CreateInternalInvoluteGear command is included in the master branch of the FCGear workbench. So now this workbench should work with the default FCGear workbench.
